--DROP TABLE MFA_INFO;
--DROP INDEX IDX_MFA_INFO_ISSUER_BANK_ID_ACCOUNT;

--DROP SEQUENCE MFA_INFO_SEQ;

CREATE TABLE "MFA_INFO"(
  "ID" NUMBER(19) PRIMARY KEY,
  "ISSUER_BANK_ID" NUMBER(19) NOT NULL,
  "ACCOUNT" VARCHAR(50) NOT NULL,
  "SECRET_KEY" CHAR(32) NOT NULL
)

CREATE INDEX "IDX_MFA_INFO_1" ON "MFA_INFO"("ISSUER_BANK_ID", "ACCOUNT");

CREATE SEQUENCE "MFA_INFO_SEQ" minvalue 1 maxvalue 999999999999999999999999999 increment by 1 NOCYCLE;

COMMENT ON COLUMN "MFA_INFO"."ID" IS 'ID';
COMMENT ON COLUMN "MFA_INFO"."ISSUER_BANK_ID" IS '銀行代碼';
COMMENT ON COLUMN "MFA_INFO"."ACCOUNT" IS '使用者帳號';
COMMENT ON COLUMN "MFA_INFO"."SECRET_KEY" IS '密鑰';
